In [1]:
 %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

from sklearn import tree

In [2]:
data = pd.read_csv('./Resources/WA_Fn-UseC_-Marketing-Customer-Value-Analysis.csv')
data.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [3]:
# Remove uneccessary variables
new_data = data.drop(columns=['Effective To Date', 'Customer'])
new_data

,State,Customer Lifetime Value,Response,Coverage,Education,EmploymentStatus,Gender,Income,Location Code,Marital Status,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,Washington,2763.519279,No,Basic,Bachelor,Employed,F,56274,Suburban,Married,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,Arizona,6979.535903,No,Extended,Bachelor,Unemployed,F,0,Suburban,Single,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,Nevada,12887.431650,No,Premium,Bachelor,Employed,F,48767,Suburban,Married,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,California,7645.861827,No,Basic,Bachelor,Unemployed,M,0,Suburban,Married,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,Washington,2813.692575,No,Basic,Bachelor,Employed,M,43836,Rural,Single,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,California,23405.987980,No,Basic,Bachelor,Employed,M,71941,Urban,Married,...,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
9130,California,3096.511217,Yes,Extended,College,Employed,F,21604,Suburban,Divorced,...,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
9131,California,8163.890428,No,Extended,Bachelor,Unemployed,M,0,Suburban,Single,...,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
9132,California,7524.442436,No,Extended,College,Employed,M,21941,Suburban,Married,...,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
9133,California,2611.836866,No,Extended,College,Unemployed,M,0,Suburban,Single,...,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [4]:
# Add a column of LTV. thsi coulumn will determine if a customer is considered high valueble or not 
#new_data.loc[new_data['Customer Lifetime Value'] <= 5000, 'LTV'] = "0"
#new_data.loc[new_data['Customer Lifetime Value'] > 5000, 'LTV'] = "1"

#new_data.head()

In [5]:
new_data.loc[(new_data['Customer Lifetime Value'] >0) & (new_data['Customer Lifetime Value']<= 3994.26), 'LTV'] = 4 
new_data.loc[(new_data['Customer Lifetime Value'] > 3994.26)& (new_data['Customer Lifetime Value'] <= 5780.182197), 'LTV'] = 3
new_data.loc[(new_data['Customer Lifetime Value'] > 5780.19) & (new_data['Customer Lifetime Value']<= 8962.16), 'LTV'] = 2
new_data.loc[(new_data['Customer Lifetime Value'] > 8962.17), 'LTV'] = 1
new_data.head(50)

,State,Customer Lifetime Value,Response,Coverage,Education,EmploymentStatus,Gender,Income,Location Code,Marital Status,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,LTV
0,Washington,2763.519279,No,Basic,Bachelor,Employed,F,56274,Suburban,Married,...,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize,4.0
1,Arizona,6979.535903,No,Extended,Bachelor,Unemployed,F,0,Suburban,Single,...,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize,2.0
2,Nevada,12887.431650,No,Premium,Bachelor,Employed,F,48767,Suburban,Married,...,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize,1.0
3,California,7645.861827,No,Basic,Bachelor,Unemployed,M,0,Suburban,Married,...,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize,2.0
4,Washington,2813.692575,No,Basic,Bachelor,Employed,M,43836,Rural,Single,...,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize,4.0
5,Oregon,8256.297800,Yes,Basic,Bachelor,Employed,F,62902,Rural,Married,...,0,2,Personal Auto,Personal L3,Offer2,Web,159.383042,Two-Door Car,Medsize,2.0
6,Oregon,5380.898636,Yes,Basic,College,Employed,F,55350,Suburban,Married,...,0,9,Corporate Auto,Corporate L3,Offer1,Agent,321.600000,Four-Door Car,Medsize,3.0
7,Arizona,7216.100311,No,Premium,Master,Unemployed,M,0,Urban,Single,...,0,4,Corporate Auto,Corporate L3,Offer1,Agent,363.029680,Four-Door Car,Medsize,2.0
8,Oregon,24127.504020,Yes,Basic,Bachelor,Medical Leave,M,14072,Suburban,Divorced,...,0,2,Corporate Auto,Corporate L3,Offer1,Agent,511.200000,Four-Door Car,Medsize,1.0
9,Oregon,7388.178085,No,Extended,College,Employed,F,28812,Urban,Married,...,0,8,Special Auto,Special L2,Offer2,Branch,425.527834,Four-Door Car,Medsize,2.0
10,California,4738.992022,No,Basic,College,Unemployed,M,0,Suburban,Single,...,0,3,Personal Auto,Personal L3,Offer1,Agent,482.400000,Four-Door Car,Small,3.0
11,California,8197.197078,No,Basic,College,Unemployed,F,0,Suburban,Married,...,0,3,Personal Auto,Personal L3,Offer2,Agent,528.000000,SUV,Medsize,2.0
12,California,8798.797003,No,Premium,Master,Employed,M,77026,Urban,Married,...,2,3,Corporate Auto,Corporate L1,Offer2,Agent,472.029737,Four-Door Car,Medsize,2.0
13,Arizona,8819.018934,Yes,Basic,High School or Below,Employed,M,99845,Suburban,Married,...,1,8,Corporate Auto,Corporate L3,Offer2,Branch,528.000000,SUV,Medsize,2.0
14,California,5384.431665,No,Basic,College,Employed,M,83689,Urban,Single,...,2,8,Corporate Auto,Corporate L3,Offer4,Call Center,307.139132,Four-Door Car,Medsize,3.0
15,Oregon,7463.139377,No,Basic,Bachelor,Employed,F,24599,Rural,Married,...,1,2,Corporate Auto,Corporate L2,Offer2,Branch,42.920271,Four-Door Car,Medsize,2.0
16,Nevada,2566.867823,No,Basic,High School or Below,Medical Leave,M,25049,Suburban,Married,...,0,1,Personal Auto,Personal L3,Offer2,Call Center,454.245098,Two-Door Car,Medsize,4.0
17,California,3945.241604,No,Basic,College,Medical Leave,M,28855,Suburban,Married,...,0,1,Personal Auto,Personal L2,Offer3,Call Center,647.442031,SUV,Medsize,4.0
18,Oregon,5710.333115,No,Basic,College,Employed,M,51148,Urban,Married,...,0,7,Personal Auto,Personal L2,Offer2,Branch,308.981664,Four-Door Car,Medsize,3.0
19,California,8162.617053,No,Premium,High School or Below,Employed,F,66140,Suburban,Married,...,0,3,Corporate Auto,Corporate L2,Offer1,Call Center,484.800000,Four-Door Car,Small,2.0
20,Oregon,2872.051273,No,Basic,High School or Below,Employed,M,57749,Suburban,Single,...,0,1,Personal Auto,Personal L2,Offer1,Branch,355.200000,Two-Door Car,Medsize,4.0
21,Washington,3041.791561,No,Extended,Bachelor,Disabled,F,13789,Suburban,Divorced,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,379.200000,Four-Door Car,Medsize,4.0
22,Arizona,24127.504020,Yes,Basic,Bachelor,Medical Leave,M,14072,Suburban,Divorced,...,0,2,Personal Auto,Personal L3,Offer1,Agent,511.200000,Four-Door Car,Medsize,1.0
23,Nevada,2450.190996,No,Basic,Bachelor,Unemployed,F,0,Suburban,Single,...,3,1,Corporate Auto,Corporate L3,Offer1,Branch,554.376763,Four-Door Car,Medsize,4.0
24,California,2392.107890,No,Basic,Bachelor,Disabled,F,17870,Suburban,Married,...,0,1,Corporate Auto,Corporate L2,Offer2,Branch,439.200000,Four-Door Car,Medsize,4.0
25,Oregon,5802.065978,No,Basic,College,Employed,M,97541,Suburban,Married,...,0,3,Personal Auto,Personal L3,Offer2,Call Center,389.185006,Four-Door Car,Large,2.0
26,California,3946.372085,No,Premium,Bachelor,Unemployed,F,0,Suburban,Single,...,0,1,Personal Auto,Personal L3,Offer1,Agent,799.200000,Four-Door Car,Small,4.0
27,Washington,5346.916576,No,Extended,Master,Disabled,F,10511,Urban,Married,...,0,1,Corporate Auto,Corporate L1,Offer1,Branch,516.237951,SUV,Medsize,3.0
28,Arizona,12902.560140,No,Premium,College,Employed,F,86584,Suburban,Single,...,2,2,Personal Auto,Personal L3,Offer1,Call Center,532.800000,Four-Door Car,Large,1.0
29,Oregon,3235.360468,No,Extended,Master,Employed,F,75690,Suburban,Married,...,1,1,Personal Auto,Personal L3,Offer2,Branch,384.000000,Four-Door Car,Small,4.0
30,Arizona,2454.583540,No,Basic,College,Employed,M,23158,Suburban,Married,...,1,1,Personal Auto,Personal L2,Offer4,Call Center,322.294043,Four-Door Car,Small,4.0
31,Nevada,18975.456110,No,Extended,High School or Below,Employed,M,65999,Urban,Married,...,0,6,Corporate Auto,Corporate L2,Offer2,Agent,615.927769,Luxury SUV,Medsize,1.0
32,California,4715.321344,No,Basic,Bachelor,Unemployed,M,0,Urban,Married,...,0,3,Personal Auto,Personal L3,Offer1,Call Center,308.150890,Four-Door Car,Medsize,3.0
33,Washington,5018.885233,No,Basic,Bachelor,Employed,M,54500,Suburban,Married,...,0,6,Corporate Auto,Corporate L2,Offer1,Agent,302.400000,Two-Door Car,Small,3.0
34,Oregon,4932.916345,No,Basic,Bachelor,Employed,F,37260,Rural,Married,...,0,8,Corporate Auto,Corporate L1,Offer3,Web,15.437681,Four-Door Car,Medsize,3.0
35,Arizona,5744.229745,No,Basic,High School or Below,Employed,F,68987,Urban,Married,...,0,6,Personal Auto,Personal L1,Offer1,Branch,204.475147,Four-Door Car,Medsize,3.0
36,California,13891.735670,No,Premium,Bachelor,Employed,M,42305,Suburban,Married,...,0,2,Personal Auto,Personal L3,Offer1,Agent,561.600000,Four-Door Car,Small,1.0
37,Oregon,7380.976717,No,Extended,Master,Employed,F,65706,Suburban,Married,...,0,8,Personal Auto,Personal L3,Offer2,Web,436.800000,Four-Door Car,Small,2.0
38,Oregon,3090.034104,No,Extended,Bachelor,Unemployed,M,0,Suburban,Single,...,0,1,Personal Auto,Personal L2,Offer3,Agent,648.000000,Two-Door Car,Small,4.0
39,Arizona,2521.633095,No,Basic,High School or Below,Employed,M,53243,Rural,Divorced,...,2,1,Personal Auto,Personal L3,Offer1,Call Center,157.397849,Four-Door Car,Medsize,4.0
40,Nevada,2652.061785,No,Basic,High School or Below,Unemployed,F,0,Suburban,Married,...,1,1,Corporate Auto,Corporate L3,Offer3,Call Center,484.318536,Two-Door Car,Medsize,4.0
41,Oregon,2771.045031,Yes,Basic,College,Employed,F,50071,Rural,Single,...,0,1,Corporate Auto,Corporate L3,Offer2,Agent,18.918935,Two-Door Car,Medsize,4.0
42,California,3939.006370,Yes,Extended,Bachelor,Employed,F,60021,Suburban,Married,...,0,1,Personal Auto,Personal L2,Offer2,Agent,882.871945,Four-Door Car,Small,4.0
43,Arizona,12231.879680,No,Basic,High School or Below,Employed,M,43244,Suburban,Married,...,0,2,Personal Auto,Personal L2,Offer4,Agent,494.400000,Sports Car,Medsize,1.0
44,Washington,2443.665166,No,Basic,College,Employed,M,92834,Suburban,Married,...,0,1,Special Auto,Special L2,Offer2,Call Center,292.800000,Four-Door Car,Large,4.0
45,Oregon,12819.102890,No,Premium,Doctor,Disabled,F,10105,Rural,Married,...,3,3,Personal Auto,Personal L2,Offer1,Branch,0.517753,SUV,Medsize,1.0
46,Arizona,4468.510542,No,Basic,Bachelor,Unemployed,M,0,Suburban,Single,...,3,5,Personal Auto,Personal L3,Offer3,Call Center,579.165954,Four-Door Car,Medsize,3.0
47,Oregon,5514.344018,No,Basic,High School or Below,Employed,F,23218,Suburban,Single,...,0,4,Personal Auto,Personal L2,Offer4,Agent,447.793440,Two-Door Car,Medsize,3.0
48,California,3343.875326,No,Extended,Bachelor,Unemployed,F,0,Suburban,Married,...,0,1,Corporate Auto,Corporate L2,Offer2,Call Center,529.624084,Four-Door Car,Medsize,4.0
49,Arizona,2294.478927,No,Basic,High School or Below,Unemployed,F,0,Suburban,Married,...,0,1,Personal Auto,Personal L2,Offer4,Branch,313.023175,Four-Door Car,Medsize,4.0

In [6]:
new_data_LTV = new_data.drop(columns=['Customer Lifetime Value'])
new_data_LTV.head()

,State,Response,Coverage,Education,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,LTV
0,Washington,No,Basic,Bachelor,Employed,F,56274,Suburban,Married,69,...,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize,4.0
1,Arizona,No,Extended,Bachelor,Unemployed,F,0,Suburban,Single,94,...,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize,2.0
2,Nevada,No,Premium,Bachelor,Employed,F,48767,Suburban,Married,108,...,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize,1.0
3,California,No,Basic,Bachelor,Unemployed,M,0,Suburban,Married,106,...,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize,2.0
4,Washington,No,Basic,Bachelor,Employed,M,43836,Rural,Single,73,...,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize,4.0

In [7]:
# Dummy coding for categorical variables (get_dummies)

data_binary_encoded = pd.get_dummies(new_data_LTV, columns=['State','Response', 'Coverage', 'Education', 'EmploymentStatus', 'Gender', 'Location Code',
       'Marital Status', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Vehicle Class', 'Vehicle Size'])
data_binary_encoded.head()

,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount,LTV,State_Arizona,State_California,...,Sales Channel_Web,Vehicle Class_Four-Door Car,Vehicle Class_Luxury Car,Vehicle Class_Luxury SUV,Vehicle Class_SUV,Vehicle Class_Sports Car,Vehicle Class_Two-Door Car,Vehicle Size_Large,Vehicle Size_Medsize,Vehicle Size_Small
0,56274,69,32,5,0,1,384.811147,4.0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,94,13,42,0,8,1131.464935,2.0,1,0,...,0,1,0,0,0,0,0,0,1,0
2,48767,108,18,38,0,2,566.472247,1.0,0,0,...,0,0,0,0,0,0,1,0,1,0
3,0,106,18,65,0,7,529.881344,2.0,0,1,...,0,0,0,0,1,0,0,0,1,0
4,43836,73,12,44,0,1,138.130879,4.0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [8]:
# Define target 
target = data_binary_encoded["LTV"]
target_names = ["negative", "positive"]

In [9]:
data_1 = data_binary_encoded.drop("LTV", axis=1)
feature_names = data_1.columns

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_1, target, random_state=42)

In [11]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9246935201401051